### PR TITLE
Support MySQL 8.0.1 and above

### LINKED ISSUE #24: Support MySQL 8.0.1+
Hi,

MySQL 8.0.1+ now supports the `SKIP LOCKED` directive. I believe it would be useful to extend this library to also support MySQL users.

I have a PR ready that supports both PostgreSQL and MySQL if you're interested :-) Do let me know :-)

-=david=-

### PR DESCRIPTION
**Pull request by dharrigan**
MySQL 8.0.1 and above now supports the SKIP LOCKED directive
Moving of files around to allow the introduction of MySQL SQL 
Documentation updates

fixes #24

-=david=-

### CODE REVIEW

**Comment by dharrigan** [comment]
Hi, just wondering if you have given any consideration to this PR? Happy to address any feedback you may have. Thank you.

**Comment by msolli** [comment]
Sorry for the delay. I've looked at the changes, and it looks like something we can move forward with. I'll try assign a work slot to kick the tires and give proper feedback later this week.

**Comment by dharrigan** [comment]
Hi,

Thanks for the update. I'm using it already (my branch) and it appears to work well - however, that's not to say it can improved upon! :-) I await your feedback. 

-=david-=

**Comment by msolli** [comment]
Thanks for the PR! Works as advertised. Next I'll work on the examples to make them work for both databases.

I'll do a release later, but I want to to include some more planned work there.

**Comment by dharrigan** [comment]
Hi!

That's awesome! Looking forward to the next release!

Thank you for the consideration of my PR.

-=david=-

**Pull request merged**
